### ISSUE TITLE
Autocomplete tags with prefixes

### ISSUE THREAD

**Issue by bakape** [bakape/hydron#17]
Prefixes are not accounted for right now. Need to both accept prefixed tags for completion and return prefixed results.

**Comment by Kamuso** [comment]
Should the prefix itself be autocompleted too? E.g. syst would have system: as an autocomplete result.
Also, it looks like #25 is a duplicate issue.

**Comment by bakape** [comment]
>Should the prefix itself be autocompleted too? 

It should. 

>Also, it looks like #25 is a duplicate issue.

It's separate because #17 is just an extension of the current completion (just strings) but #25 should autocomplete syntax.
