### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [bakape/hydron#18]
Greetings,

I'm a graphic designer and I would be more than happy to contribute to your project by creating a logo for it. It's completely free and both of us will beneficiate from it (I will expand my portfolio) let me know if you are interested.

Best regards.

**Comment by bakape** [comment]
Sure, thanks! The logo will be used for an application icon and a favicon, so a roughly 1x1 aspect ratio  is probably best.

**Comment by michaelizer** [comment]
I'd like to ask some questions before starting, your answers will help me to deliver a better product.

   - What's the name that should be displayed on the logo?, If there should be any.
   - How would you describe this project and What is it intended to do?
   - What would you like this logo to transmit?

I'll look forward to your reply, kind regards.

**Comment by bakape** [comment]
>What's the name that should be displayed on the logo?, If there should be
any.
Probably none. It's supposed to fit on a favicon.
>How would you describe this project and What is it intended to do?
Aggregate images and tags off boorus, Twitter, Pixiv, Hydrus, etc. into
your own personal (for now) media organizer. At least that much is planned
for when this project reaches maturity.
> What would you like this logo to transmit?
Whatever will do.

**Comment by michaelizer** [comment]
So sorry for the delay, I want to start with these sketches. What do you think? I tried to make them simpler enough to fit a favicon, but I want your opinion 
![imagen](https://user-images.githubusercontent.com/35619342/42513056-01e8d512-8424-11e8-9c0c-8382c1a09341.png)

**Comment by bakape** [comment]
The teal one looks best, in my opinion.

On 10 Jul 2018 4:31 pm, "michaelizer" <notifications@github.com> wrote:

So sorry for the delay, I want to start with these sketches. What do you
think? I tried to make them simpler enough to fit a favicon, but I want
your opinion
[image: imagen]
<https://user-images.githubusercontent.com/35619342/42513056-01e8d512-8424-11e8-9c0c-8382c1a09341.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bakape/hydron/issues/18#issuecomment-403822901>, or mute
the thread

**Comment by michaelizer** [comment]
This one? 
![imagen](https://user-images.githubusercontent.com/35619342/42513770-c265e8c4-8425-11e8-981b-dbb91451b304.png)

Anything specific you want to add/modify. Like the color (you can give me the color code to be precise). If not, let me know :d

**Comment by bakape** [comment]
No, the lighter blue rectangular one. It seems fine as it is.

**Comment by michaelizer** [comment]
Perfect! I'll make the proper files then.

**Comment by michaelizer** [comment]
Done, added the logo (solo) in .svg format, check it [here](https://drive.google.com/open?id=1uGSP2ujPwdSE70XDpjEji-d_NSV7XlN1)

**Comment by bakape** [comment]
Okay, thanks!
