### ISSUE TITLE
Where is the database located?

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#19]
Or for that matter, the thumbnails themselves?
Can I just delete or otherwise modify the database myself with `sudo dropdb hydron`?

**Comment by bakape** [comment]
See https://github.com/bakape/hydron/blob/master/files/dirs.go#L19-L26 and
you can delete the entire directory just fine, but don't modify the files
inside.

**Comment by ghost** [comment]
Thank you, that helps.

**Comment by daephx** [comment]
Was looking for related issues, just curious on your thoughts for custom database locations?

**Comment by bakape** [comment]
It's fine as long as there is a decent way to pass it.

**Comment by daephx** [comment]
Alright, wasn't sure if it wasn't already available in some form.
I know hydrus does something like `client.exe -database="path\to\db\"`. For now I'm just symlinking to a larger external drive "E:\hydron\database\" as "C:\" just doesn't have the size available for my library.
