### ISSUE TITLE
Tag completion web

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#22]
Tag completion only works after pressing or clicking something other than the search box.
Probably need to move an event listener to the init instead of onClick or onPress.

**Comment by bakape** [comment]
Browser and version?

**Comment by ghost** [comment]
Firefox, 61.0.1.

**Comment by bakape** [comment]
Want to try working around that broken as fuck browser?

**Comment by ghost** [comment]
I don't even know where to start on this, if I did I'd have submitted a PR and not an issue.

**Comment by bakape** [comment]
Fine. I'll try at least.

**Comment by ghost** [comment]
Thank you.

**Comment by bakape** [comment]
Basically autofocus is broken in FF. I can either give this to you or close it with won't_fix.

**Comment by ghost** [comment]
Autofocus? Is that something on the Firefox dev's side or is it something fixable with JS?
I'll try my hand at it if it's fixable with JS.

**Comment by bakape** [comment]
It's fucked on the FF side. You can try to find a workaround for this broken browser with some JS. FF is the new IE. Enjoy!

**Comment by ghost** [comment]
You know what, I'm already using a botnet, I'll just use Chromium, because fuck this shit.
`¯\_(ツ)_/¯`
I wish there were better browsers.

**Comment by bakape** [comment]
Brave seems decent. Maybe still not mature enough though. At least it's lead by Brendan Eich.

**Comment by ghost** [comment]
I tried Brave, and it's "okay", but I might as well use Falkon in that case, which suffers from it's own issues.
