### ISSUE TITLE
Watching directories for new imports

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#23]
Probably just run a hash check and if new/altered, import the image and remove the replaced image, if applicable.

**Comment by bakape** [comment]
What?

**Comment by ghost** [comment]
Being able to have access to new or altered images without having to reimport the folder each time would be nice.

**Comment by bakape** [comment]
But images in the database are immutable. Only tags mutate.

**Comment by ghost** [comment]
Yes, but when I change or add something in `/home/okina/Pictures`, I want hydron to reflect that either immediately or every start of hydron, without having to import the entire folder each time.

**Comment by bakape** [comment]
Importing an image performs a copy. It is in no way tied to your personal
image storage directories.

**Comment by ghost** [comment]
Yes, I know.
I want hydron to find out if the local copy differs from the original copy, and if it does, replace the local with the (new) "original".

**Comment by bakape** [comment]
And how do you think that would ever be possible without you turning your
personal folders over to VCS?

**Comment by ghost** [comment]
Keep a database of hashes which you already do, and check if the hash is the same.
If not, replace/add to the local copy.

**Comment by bakape** [comment]
No, you don't understand. I can check, if an image is in the database
already, just fine, but how can I check, if image A with hash B was
previously image C with hash D?

**Comment by ghost** [comment]
I can't say I know.
All I know is that being able to not have to import every time I start up hydron would be nice, since I have a large image folder.

**Comment by bakape** [comment]
>being able to not have to import every time I start up hydron would be nice
And you don't have to. Import is a one time thing.

**Comment by ghost** [comment]
I don't have to, sure.
But if I want the two images I just added to my Pictures folder, I have to re-run it, in addition to fetch_tags, which takes a while too.

**Comment by bakape** [comment]
Then just add them separately with the -f flag. Otherwise you will have to
rehash every file in the directory to check for matches.

**Comment by ghost** [comment]
Having to have a separate directory for newly saved images is silly just so I could do that, waaay too much maintenance.
There has to be a smart way to at the very least, find new images and fetch their tags without reimporting.

**Comment by bakape** [comment]
Import already does that. The problem is it still has to read and hash
every file in your directory tree to check for matches.

**Comment by ghost** [comment]
How about this then, a possible middleground between performance and ease-of-use.
A slow import and fetch that's always running, so it doesn't bring the system to a hault or otherwise take up too much CPU.
Or, a slightly faster import and fetch that happens every X amount of time.
That way, we don't have to run import to update for new/altered images and fetch_tags for tags, since both will either always be running or being ran every increment of time.

**Comment by bakape** [comment]
http://man7.org/linux/man-pages/man7/inotify.7.html and
https://github.com/fsnotify/fsnotify. Want to have a jab at this?

**Comment by ghost** [comment]
Sure, but it might take me a while to get to.

**Comment by bakape** [comment]
It's fine. I don't consider this core functionality anyway.

**Comment by ghost** [comment]
@bakape Could you give me collaborator permissions on this repo too so I can make branches here like meguca?
I changed up my local stuff to make branches on meguca directly, so I'd like to do it on hydron too for whenever I get to this.

**Comment by bakape** [comment]
Done.

**Comment by ghost** [comment]
Watching directories with hydron may be not only a problem for hydron itself, but also the entire OS.
Read the bottom of https://github.com/fsnotify/fsnotify under "How many files can be watched at once?"
>There are OS-specific limits as to how many watches can be created:

>Linux: /proc/sys/fs/inotify/max_user_watches contains the limit, reaching this limit results in a "no space left on device" error.
BSD / OSX: sysctl variables "kern.maxfiles" and "kern.maxfilesperproc", reaching these limits results in a "too many open files" error.

**Comment by ghost** [comment]
So, just importing each time you want to add new files and trying our hardest to optimize and even skip suspected already imported files may be for the best.
Thoughts?

**Comment by ghost** [comment]
Also I know you said it was dumb, but BLAKE2 might be a good way for faster and more unique hashes, if you ever want to consider that.
https://research.kudelskisecurity.com/2017/03/06/why-replace-sha-1-with-blake2/
https://godoc.org/golang.org/x/crypto/blake2b

**Comment by bakape** [comment]
I have reduced memory usage for already imported files with d5ca369e8fd53e7dbd414fd5b4f738cf7530ec8a. 

>BLAKE2

Not an option. Whatever slow gain would be offset by the overhead of still needing SHA1 hashes and storing an extra hash per image. 

Basically, don't rescan your image folders all the fucking time. That is not how hydron was intended to be used.

**Comment by ghost** [comment]
>Not an option. Whatever slow gain would be offset by the overhead of still needing SHA1 hashes and storing an extra hash per image.

Now it makes sense why you think it's dumb, does this mean you can't put BLAKE2 hashes into the DB the same way you can SHA1? Why would you need an extra hash? I'm well aware it would require rewriting the thumbnailer and other stuff.

**Comment by bakape** [comment]
Because we still need to generate SHA1, because external services use SHA1. Same with MD5. 
So currently we generate SHA1+MD5.  With BLAKE2 we would need to generate BLAKE2+SHA1+MD5 and store the BLAKE2 hash as well. At the same time no external service I know of uses BLAKE2, so it's not reusable.

**Comment by ghost** [comment]
Okay, thank you for explaining this to me.
BLAKE2 isn't an optimization option, at least not for the foreseeable future.

**Comment by ghost** [comment]
Since you closed #32 , should we close this one too?
AFAIK using fsnotify isn't an option because of the file limit.
