### ISSUE TITLE
Expand image on click

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#30]
Instead of going to it directly, expand it in an img tag with an event listener and make it small again when clicking on it again and show tags, like the webm.

**Comment by bakape** [comment]
I think I much prefer single click to see expanded+tags. What is your reasoning for this?

**Comment by ghost** [comment]
Right now, single click on an image just goes straight to the URL.
If we expanded it inline and added an event listener to tell when it's clicked first to expand and when it's clicked second to close, we can use that first click to pull up the tags.

**Comment by bakape** [comment]
I don't implementation details. I want to know why you think that's better
design than the current one?

**Comment by ghost** [comment]
Seeing an expanded inline image with associated tags is better looking, smarter, and more useful that just going directly to the link.
You already do this with webm.
Make an event listener that checks for a click on the image, and if clicked expand and show tags, if clicked again, go back to the previous "catalog" state.
I can probably implement this if you still don't understand.

**Comment by bakape** [comment]
>You already do this with webm.
What?
I understand how to do this perfectly. I don't understand why anyone would
want this. You are making a 1 step process a 2 step process for no obvious
gain.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/30435868/43040198-7934a0a0-8d03-11e8-9191-47c583abef82.png)

**Comment by ghost** [comment]
The gain is that you get the associated tags, and if you want to go back, instead of the back arrow, just click the image.
It's a QoL improvement.

**Comment by ghost** [comment]
I was wrong about the URL part, seems like you already inline expand, but the tags don't show.
My fault for not reading the URL, or maybe something changed since the last commit.
![image](https://user-images.githubusercontent.com/30435868/43040214-ce92b280-8d03-11e8-8bc5-17eb768ab19b.png)

**Comment by ghost** [comment]
Okay, so this changes to "Let's ensure the tags always show, and click on the image to go back" instead.

**Comment by bakape** [comment]
Tags don't show, if there are no tags.

**Comment by ghost** [comment]
Okay, so I'm even more retarded then.
What do you think about "click the image to go back", then?

**Comment by ghost** [comment]
Off topic: I randomly got this while trying sort:order. Only happened once, can't seem to replicate.
![image](https://user-images.githubusercontent.com/30435868/43040241-663daea0-8d04-11e8-90e8-f037d3fce944.png)

**Comment by bakape** [comment]
Reasonable, but would conflict with video behaviour, that does not close on click. Also, breaks on FireFox :^)

**Comment by ghost** [comment]
We could just do it for non-video, then. Fuck Firefox at this point.

**Comment by bakape** [comment]
Well, it says you made a syntax error. What did you input?

**Comment by ghost** [comment]
Like I said, `sort:order`.
I think it was after clicking an image tag.

**Comment by ghost** [comment]
Rather, `sort:order` shows nothing when on the initial page.

**Comment by ghost** [comment]
And anywhere else, I guess.
I had it work sometimes when doing a reimport and a deletion of the .hydron folder.

**Comment by bakape** [comment]
`sort:` is not even and internal tag.

**Comment by bakape** [comment]
RTFM

**Comment by ghost** [comment]
I'm retarded, I meant `sort:random`, but that makes sense now.
It's `order:random`, isn't it?
Mind pointing me to the FM?

**Comment by bakape** [comment]
`hydron --help`

**Comment by ghost** [comment]
Maybe I should start drinking coffee.
Thanks lat.

**Comment by ghost** [comment]
Ah, on the topic of the original post, I'll implement going back by click for non-video images.

**Comment by bakape** [comment]
Also, this is not obvious, but you can also use Esc to exit ImageView like in any decent image viewer.

**Comment by ghost** [comment]
I didn't know that. Thanks again.
