### ISSUE TITLE
Missing dependency Git for building

### ISSUE THREAD

**Issue by DrakaSAN** [bakape/hydron#31]
It s easy to miss for thoses that would usually build this project, git is a dependency for the command as written.

The readme about the dependencies may also be improved by showing the exact packages on the main(s) distribution, `apt` would be a good choice seeing that all Debian derivative, Ubuntu included, use it.

```sh
sudo apt install gcc pkg-config git golang cmake libgtk2.0-dev libavcodec-dev libavformat-dev libswscale-dev libmagickwand-dev
```
Wonderfull work by the way, even though as a user it still miss some critical features for me, I ll be following it s evolution

**Comment by bakape** [comment]
>git
Will add
>libgtk2.0-dev
What?
>cmake
uneeded
>libmagickwand-dev
Except we don't use the MagicWand API.

**Comment by DrakaSAN** [comment]
You're right for libgtk, went overboard when trying to find the missing dependencies, same for cmake. The danger of hasty copy paste.
I ll try again once I have the right computer on hand, and will make a better effort at pinpointing the right dependencies.
