### ISSUE TITLE
hydron import takes too much memory

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#32]
Perhaps have hydron check how much memory there is, allocate in chunks of 256MiB, until there is X amount of memory total left unused for other programs?
I'd rather my entire computer not lock, please.

**Comment by bakape** [comment]
Working on it.

**Comment by bakape** [comment]
Also, see https://github.com/bakape/thumbnailer/issues/24

**Comment by ghost** [comment]
The Go FFI would create this much memory bloat on import?

**Comment by bakape** [comment]
Not as much, but it's not negligible. Also, I think the crux of your
problem is scanning file you already have imported. That creates tons of
garbage.

**Comment by ghost** [comment]
I remove the .hydron folder, drop the db, recreate the db, have hydron initialize normally, add db_conf.json, then have hydron initialize with postgres.

**Comment by bakape** [comment]
Is this still relevant?

**Comment by ghost** [comment]
I'll have to check later, but even without that, I noticed something you did, not sure what, did reduce memory usage earlier.
Only about 8GiB was being used, which is still a lot, but much better than everything+16GiB swap.
I'll test and close if it's significantly better in a bit.

**Comment by bakape** [comment]
The Go runtime will naturally increase its memory pool, if there is more
available, and won't return it to the OS immediately.

**Comment by ghost** [comment]
Are we reusing memory where possible?
Maybe `GODEBUG=gctrace=1` might help here?

**Comment by ghost** [comment]
Or, if it's because of the goroutines, maybe clean them up more often at the expense of some speed.
I feel garbage is piling up with the import goroutines and we're probably not cleaning it often enough, thus why the Go runtime keeps increasing it's memory pool.
That might have changed with your recent commit, though.

**Comment by bakape** [comment]
The Go runtime will always increase heap memory, if it can. Welcome to GC
languages.

On 13 Aug 2018 2:56 pm, "チルノ" <notifications@github.com> wrote:

Or, if it's because of the goroutines, maybe clean them up more often at
the expense of some speed.
I feel garbage is piling up with the import goroutines and we're probably
not cleaning it often enough, thus why the Go runtime keeps increasing it's
memory pool.
That might have changed with your recent commit, though.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bakape/hydron/issues/32#issuecomment-412493965>, or mute
the thread

**Comment by ghost** [comment]
aaaaaaaaaaaaaaaaaaaaaa this is why i hate garbage collection

**Comment by bakape** [comment]
Rewrite thumbnailer in Rust and we could honestly rewrite hydron to it.

**Comment by ghost** [comment]
Rust isn't ready. I don't want to write shit in it until 2.0, where it won't be shit.
1.0 was a fucking farce.
Could rewrite it in C++, but at that point might as well wait for Rust 2.0.

**Comment by ghost** [comment]
Also, at least in Rust or C/C++, we can keep tabs on how much memory there is available, and allocate where necessary in chunks. I think that might be possible in Go, but I feel it may be counter-productive with the GC.

**Comment by bakape** [comment]
Or provide a pure C/C++ interface for the existing thumbnailer. That is
probably the least painful route and still accomplish our goals.

**Comment by ghost** [comment]
That could work, but at the same time the thumbnailer is small enough that you might as well rewrite it in C++ too.
You're right, though. C/C++ interface until Rust 2.0 is probably the most productive path.

**Comment by bakape** [comment]
The brunt of it is already in C so you really just need to rewrite the
little Go logic there to C and still keep a Go interface to it.

**Comment by ghost** [comment]
Importing already imported files memory usage is SIGNIFICANTLY better, I think it only used like 200MiB total, if even that. Good job, that's like night and day.
The initial import seems slightly better memory-wise, so I think we need to focus on that now.
It's your call if you want to close this issue now or later, but the initial import is still pretty big, and would be really bad for people with 100,000+ images.

**Comment by ghost** [comment]
Also I think it skips fetching tags too if already imported, so that means my nix expression won't have to DDoS Gelbooru.

**Comment by ghost** [comment]
Also, since #23 is a problem, and the new import is good, do you think we should close #23 ?
