### ISSUE TITLE
Add special name:X tag for specifying download file names

### ISSUE THREAD

**Issue by bakape** [bakape/hydron#35]

**Comment by ghost** [comment]
Wait, so you want to add a configurable name tag to a file?
Through the terminal command or through the interface?

**Comment by bakape** [comment]
Notice how we have namespaced tags like artist:X and series:Y? Basically
another one of these.

**Comment by ghost** [comment]
Okay, do we have to rename the file to the name:X tag too, or are we doing only a new tag?

**Comment by ghost** [comment]
Or maybe I'm reading that wrong, are we making the name:X tag after the original file name?

**Comment by bakape** [comment]
Well, if we ignore how exactly to store a name for now, we could read the
original file name into the name:x tag (if we do in fact store it as a tag
and not a separate field). Then, when we export the file using drag&drop or
download, we can apply this name to the file.
