### ISSUE TITLE
Fetch image rating from gelbooru JSON API

### ISSUE THREAD

**Issue by bakape** [bakape/hydron#44]
An extra request in addition to the page fetch is required.

**Comment by bakape** [comment]
A better approach would be to retrieve the image ID + rating from the API and then extract the tags with categories from the image HTML page.

**Comment by gelbooru** [comment]
We have had a tags API for years as well. Please update your code and use that. Thanks.

**Comment by bakape** [comment]
The problem is your tag API does not include categories (or did not, when I wrote this), but tags in HTML are grouped by category. Feel free to correct me, when that changes.

**Comment by gelbooru** [comment]
It's been around since at least December 1st, 2012

https://gelbooru.com/index.php?page=wiki&s=view&id=18780

**Comment by bakape** [comment]
Closed with a7e87a17b889d965f442edd5d432ad7e5f51c1ca
