### ISSUE TITLE
Name field needs to be truncated to a set length

### ISSUE THREAD

**Issue by ghost** [bakape/hydron#47]
Files with long names mess up the image positioning when viewing with tags/name.
Probably should truncate the name with JS or in qtpl to a set limit so the image isn't way off to the side.

**Comment by bakape** [comment]
See https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by ghost** [comment]
Oh that's right, we've been over this before with the song title banner.
Just need to make the name field within a class span, then maybe.
